#!/usr/bin/env node
// vim: set ft=javascript

const knex = require('knex')

const connection = knex(require('../tests/knexfile'))

connection.migrate.rollback()
  .then(() => {
    console.log('Successfully reverted the database')

    connection.destroy(() => {
      process.exit(0)
    })
  })
  .catch(err => {
    console.warn(err)
    process.exit(1)
  })
